# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLMetatags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_column=b'path', help_text=b"Could be a url name or a path. Begin paths with '/'", max_length=255)),
                ('title', models.TextField(blank=True, help_text=b'Will be stuck within the title attribute', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text=b'Meta-Description', null=True)),
                ('keywords', models.TextField(blank=True, help_text=b'Meta-Keywords', null=True)),
                ('google_pagetrack_category', models.CharField(blank=True, max_length=55, null=True)),
                ('google_pagetrack_customvar', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
    ]
